[package]
name = "dotmate"
version = "0.1.0"
edition = "2021"


[dependencies]
colored = "2.0.0"
lazy_static = "1.4.0"
ron = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.21"
